version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - $PORT:$PORT
    env_file: ./.env
    volumes:
      - .:/app
      - '/app/node_modules'
    depends_on:
      - mysql_server

  mysql_server:
    image: mysql:8.0

    env_file: ./.env
    command: --init-file /data/application/init.sql
    environment:
      - MYSQL_DATABASE=$MYSQL_DB_NAME
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
    ports:
      - $MYSQL_PORT:$MYSQL_PORT
    volumes:
      - db:/var/lib/mysql
      - ./init.sql:/data/application/init.sql

volumes:
  db:
